### ISSUE TITLE
use Jon's `ansi-*`

### ISSUE THREAD

**Issue by tunnckoCore** [studio-b12/get-comments-cli#1]
jon exports every style from chalk to separate libs `ansi-*` and also `*-symbol` because chalk is big and takes a lot to load

i.e error-symbol, success-symbol, ansi-gray, ansi-red and etc.

https://github.com/jonschlinkert/ansi-gray

**Comment by tomek-he-him** [comment]
Hm, not bad! Does it detect if color isn’t supported on a terminal?

**Comment by tunnckoCore** [comment]
> Does it detect if color isn’t supported on a terminal?

nope, you can just use `support-colors` or what it was.

think modular

**Comment by tomek-he-him** [comment]
Sorry, I still see no advantage of this:

``` js
require('supports-color') ? require('ansi-bold')('SYNOPSIS') : 'SYNOPSIS'
```

over this:

``` js
require('chalk').bold('SYNOPSIS')
```

Chalk keeps to best practices, is proven and easy to use. I haven’t ever experienced a performance or memory problem it caused. If you have, please share.

**Comment by tunnckoCore** [comment]
> Sorry, I still see no advantage of this:

And you think require-ing one big module for just one bold thing is normal?! lol, okey!

/cc @jonschlinkert am I right?
